### ISSUE TITLE
bin/bash not found when using example from readme

### ISSUE THREAD

**Issue by davidcoleman007** [juho-p/fatty#31] opened 2017-10-16 15:25 UTC
When I use the example in the readme:
```
fatty -b "source $HOME/.bashrc; uname -a; exec bash"
```
![image](https://user-images.githubusercontent.com/41075/31620791-2dfcea3e-b266-11e7-885c-b93ad24f6afe.png)

I get the following window flash real fast and close:
![image](https://user-images.githubusercontent.com/41075/31620640-cb919dea-b265-11e7-9193-cc6f5289c6b4.png)

I had to use a screen capture to grab it because it was only for a frame or 2 - sorry about the desktop stuff in the bg - it says:
```
/bin/bash: uname: command not found
/bin/bash: line 0: exec: bash: command not found
```

**Comment by davidcoleman007** [comment] 2017-10-16 15:42
if I run fatty.exe just as is, nothing works, not even `ls`:
![image](https://user-images.githubusercontent.com/41075/31621190-211b3b26-b267-11e7-8ea0-199dc6d16115.png)

all tabs exhibit the same behavior in this use case:
![image](https://user-images.githubusercontent.com/41075/31621244-40b0228a-b267-11e7-867b-e587c473923b.png)

**Comment by davidcoleman007** [comment] 2017-10-16 15:45
fwiw: i do have a working cygwin, and obviously these commands work in my std cygwin terminal

**Comment by juho-p** [comment] 2017-10-31 15:04
Part of the problem is the same as https://github.com/juho-p/fatty/issues/5 which I've unfortunately been too lazy to fix.

Start fatty with command `fatty -` (note the dash)

I close this for now, since it's practically a duplicate.

**Closed as completed by juho-p** 2017-10-31 15:04 UTC
